import = [
  "/usr/lib/node_modules/alacritty-themes/themes/User 77 - Mashup colors.toml"
]
live_config_reload = true

[font]
size = 18
builtin_box_drawing = true

  [font.bold]
  family = "Fira Code Nerd Font Mono"
  # family = "FantasqueSansM Nerd Font"
  style = "Bold"

  [font.italic]
  family = "Fira Code Nerd Font Mono"
  style = "Italic"

  [font.normal]
  family = "Fira Code Nerd Font Mono"
  style = "SemiLight"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50_000
multiplier = 3

[window]
dynamic_padding = false
opacity = 0.95
